name: Test Kubernetes Connection

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: myapp-eks-cluster
  ECR_REPOSITORY: myapp_docker_repo

jobs:
  test-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          web-identity-token-file: "" 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          DOCKERFILE_PATH=$(find . -name Dockerfile -exec dirname {} \;)
          if [ -z "$DOCKERFILE_PATH" ]; then
            echo "❌ ERROR: Still could not find a file named Dockerfile anywhere in the repository!"
            exit 1
          fi
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG "$DOCKERFILE_PATH"
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # Save the full image name for the next steps
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Grant EKS Access to current IAM User
        run: |
          USER_ARN=$(aws sts get-caller-identity --query "Arn" --output text)
          aws eks create-access-entry --cluster-name ${{ env.EKS_CLUSTER_NAME }} --principal-arn "$USER_ARN" || true
          aws eks associate-access-policy --cluster-name ${{ env.EKS_CLUSTER_NAME }} \
            --principal-arn "$USER_ARN" \
            --policy-arn arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy \
            --access-scope '{"type": "cluster"}'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}

      # NEW: INJECT IMAGE AND DEPLOY TO K8S!
      - name: Deploy to EKS
        env:
          FULL_IMAGE: ${{ steps.build-image.outputs.image }}
        run: |
          # Swap out the placeholder in the YAML file with our newly built image
          sed -i "s|MY_IMAGE_PLACEHOLDER|$FULL_IMAGE|g" k8s/deployment.yaml
          
          # Apply the files!
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          
          # Wait for deployment to finish
          kubectl rollout status deployment/myapp-deployment --timeout=120s
          
          echo "Website successfully deployed!"
          echo "Run 'kubectl get svc myapp-service' to find your public URL!"
